import "@/app/globals.css";
import "./layout.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import MainContextProvider from "@/app/contexts";
import LocaleHelper from "@/app/helpers/locale";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default function RootLayout({ children, params }: Props) {
  const locale = params.locale;
  if (!LocaleHelper.isLocaleSupported(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <MainContextProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </MainContextProvider>
      </body>
    </html>
  );
}
